# Generated by Django 3.2.6 on 2021-08-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20210825_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(db_column='fullname', max_length=100),
        ),
    ]
